### ISSUE TITLE
Everything works, but the UI won't show Cron and the default config won't load

### ISSUE THREAD

**Issue by Emanuelmoves** [sidekiq-cron/sidekiq-cron#416]
From the console it all works fine, but the UI just won't show the Cron section:

```ruby
# config/schedule.yml
job_that_should_run:
  cron: '0 4 * * *'  # A cron schedule expression (runs daily at 4 AM)
  class: 'ComputeSuperStatsJob' # The name of your Active Job class
  queue: default     # The Sidekiq queue where the job will be enqueued
```

```ruby
# Gemfile.lock

sidekiq (6.5.8)
  connection_pool (>= 2.2.5, < 3)
  rack (~> 2.0)
  redis (>= 4.5.0, < 5)
sidekiq-cron (1.10.1)
  fugit (~> 1.8)
  globalid (>= 1.0.1)
  sidekiq (>= 6)

```

```ruby
Sidekiq::Web.tabs
=> {}

```

**Comment by markets** [comment]
Hello @Emanuelmoves 

Did you add the require defined in https://github.com/sidekiq-cron/sidekiq-cron#web-ui-for-cron-jobs?

**Comment by Emanuelmoves** [comment]
Hello, yes it's at the top of the routes.rb

```
require 'sidekiq/web'
require 'sidekiq/cron/web'
```

**Comment by Emanuelmoves** [comment]
It's not open-source.
I will try to setup a simpler project, this is good intel you gave me, thx.
Is there any way of debugging further meanwhile, should I look at something?

This isn't weird?
```ruby
Sidekiq::Web.tabs
=> {}
```

**Comment by markets** [comment]
Yep, that's really weird... when you add that `require`, this file is loaded: https://github.com/sidekiq-cron/sidekiq-cron/blob/master/lib/sidekiq/cron/web.rb. As you can see, the only condition there is that `Sidekiq::Web` is already loaded. 

Here I have an open-source app that works fine with that setup: https://github.com/coopdevs/timeoverflow/blob/develop/config/routes.rb#L2

**Comment by Emanuelmoves** [comment]
OK, that's interesting.

I used that code and added it to the before_action in the ApplicationController. If I do that it works, I can see the tab and it all works.

```ruby
Sidekiq::Web.register Sidekiq::Cron::WebExtension
Sidekiq::Web.tabs["Cron"] = "cron"
```

Maybe it's something related to 

ruby 3.1.3
OR
Rails 6.1.7.3

**Comment by workgena** [comment]
I had the same problem. And what was interesting is that when I've added another gem [sidekiq-failures](https://github.com/mhfs/sidekiq-failures) - it fixed the Sidekiq Web UI, and both "Failure" and "Cron" tabs appeared.

This worked because sidekiq-failures gem has this line:

https://github.com/mhfs/sidekiq-failures/blob/ff171bf8dd8fa6d87bf4449a5631162f1cce9e09/lib/sidekiq/failures.rb#L1C1-L5C4

```ruby
begin
  require "sidekiq/web"
rescue LoadError
  # client-only usage
end
```

Without sidekiq-failures gem, I've fixed this problem by doing this:

Create a file `config/initializers/sidekiq.rb` with content:

```ruby
require "sidekiq/web"
require 'sidekiq/cron/web'
```

It happened for me because my application had a custom gem dependency, let's call it `my_custom_application_scaffold` and it actually contains router.rb and some custom controllers/models which I can then use for multiple applications. And `require "sidekiq/web"` as defined inside that gem. So defining it again in the main application seems to be unnecessary. But it is still needed. I think it's because of loading order.
