### ISSUE TITLE
Task names with forward slashes cannot be enqueued manually in the web UI

### ISSUE THREAD

**Issue by kevinrobell-st** [sidekiq-cron/sidekiq-cron#452]
Let's say I have two cron tasks one with a forward slash in the name and the other without.

![Screenshot 2024-02-06 at 12 13 15 PM](https://github.com/sidekiq-cron/sidekiq-cron/assets/109554723/63218d8a-606a-49ae-b572-53cea1b3e82a)

The one with the forward slash returns a 404 when I press the `Enqueue Now` button and click okay.

![Screenshot 2024-02-06 at 12 15 17 PM](https://github.com/sidekiq-cron/sidekiq-cron/assets/109554723/d35846d3-82d1-40b1-b6a1-e51e64b0f96f)

The one without the forward slash works as expected without any problems.

![Screenshot 2024-02-06 at 12 14 49 PM](https://github.com/sidekiq-cron/sidekiq-cron/assets/109554723/f6448e08-9ca3-4f58-a551-c7104d4fd90f)

This seems like some sort of URL escaping bug at a glance. Not the end of the world though because it can easily be enqueued from the console but it's just something we ran into so I thought I'd mention it.

**Comment by markets** [comment]
> This seems like some sort of URL escaping bug

100% agree, please feel free to send a patch.

Thanks for your detailed report!

**Comment by satyakampandya** [comment]
Hi @markets @kevinrobell-st,

I wanted to get your input regarding forward slashes in job names. As mentioned, cron jobs with forward slashes in their names currently return `No route matches` when the "Enqueue Now" button is pressed, which seems to be a URL escaping issue.

To address this, we could implement a straightforward fix by adding a validation to prevent job names from containing forward slashes. However, if having forward slashes in job names is necessary for your use case, we can plan a fix to support that functionality.

Would love to hear your thoughts on this!

**Comment by markets** [comment]
> To address this, we could implement a straightforward fix by adding a validation to prevent job names from containing forward slashes

Maybe raising an error is too much 🤔, but a warning (plus documentation) is acceptable? Not sure if many people uses the UI part, so no need to restrict this probably, as this is only an issue if you want to enable/enqueue jobs from the UI.

Ideally, we should use some url-safe enconding, but let's consider the complexity we'll add by implementing this encode/decode pattern. I'm also quite sure that having those kind of chars in job names is exceptional... And the fix is easy, just rename it! Even easier if we document it somewhere and print a warning.

**Comment by satyakampandya** [comment]
@markets Any final thoughts on this? Implementing a warning along with proper documentation seems like a good approach. Since using forward slashes in job names is an uncommon use case, a warning should be sufficient to guide users without enforcing a hard restriction.

Using URL-safe encoding is a more robust solution, but it might introduce unnecessary complexity with encoding and decoding patterns.

**Comment by markets** [comment]
> Implementing a warning along with proper documentation seems like a good approach

I agree! I'd go with this. 

@kevinrobell-st What do you think?

**Comment by kevinrobell-st** [comment]
I'm in favor of the URL-safe encoding option but I'm not sure how big of a lift that is. If you'd prefer to reduce the scope of task names to avoid a larger refactor, I think that it should made to fail instead of just being a warning with documentation. I see no reason to allow the current broken behavior.

**Comment by satyakampandya** [comment]
@markets Given the differing perspectives on how to handle the job names with special characters, could you share your final thoughts on which option we should proceed with?

**Comment by markets** [comment]
Ideally, would be nice to allow URL-safe encoding names, but not sure how many changes we'll need to support that... I'd be -1 if that needs a big refactor.

Initially I thought that a warning + docs would be enough, as this only affects people using operations via the UI. But I'm also ok to raise an error... I have no strong opinion on that point.
