### ISSUE TITLE
Queue name not used as configured by sidekiq_options queue

### ISSUE THREAD

**Issue by eis-ioki** [sidekiq-cron/sidekiq-cron#470]
I noticed that when I have a job which is configured to run in a certain queue using `sidekiq_options` like this:

```ruby
class SampleJob
  include Sidekiq::Job
  sidekiq_options queue: 'sample'
end
```

And I have a `config/initializers/sidekiq_cron.rb` file like this:

```ruby
Sidekiq::Cron::Job.load_from_hash! {
  'sample_job' => {
    'class' => 'SampleJob',
    'cron'  => '0 * * * *',
  }
}
```

The `SampleJob` will be put in the `default` queue even though I configured it to run in the `sample` queue.

**Comment by markets** [comment]
Hey @eis-ioki 👋 

Yes, actually we don't support this `sidekiq_options` macro, you should pass the queue in the [job attributes](https://github.com/sidekiq-cron/sidekiq-cron?tab=readme-ov-file#job-properties). But I think it probably makes sense 🤔? Feel free to explore what is needed to support it and send a PR, if the necessary changes don't introduce a lot of complexity I'd be happy to merge it.

**Comment by fatkodima** [comment]
Are you sure that it is not working? Just tested and it works as expected.

You may have the jobs in the `"default"` queue because in your's initializer when you call `load_from_hash!`, rails classes (and the job class) are not yet loadable, meaning that you will get a `NameError` here https://github.com/sidekiq-cron/sidekiq-cron/blob/d409af416afa83362767880f57bb4bf432a80708/lib/sidekiq/cron/job.rb#L793-L801 and the first conditional branch will be executed.

What you really need to do, is wrap yours sidekiq cron definition in a little bit of code, something like:
```ruby
Rails.application.reloader.to_prepare do  # <------ this is the change
  Sidekiq::Cron::Job.load_from_hash!({
    'sample_job' => {
      'class' => 'HardWorker',
      'cron'  => '* * * * *',
    }
  })
end
```

**Comment by dcrec1** [comment]
I've running the master branch and the jobs are being enqueued like this:

![image](https://github.com/user-attachments/assets/ec8dc2cc-7706-4212-87cd-b00837afeb99)
