### ISSUE TITLE
Schedule is duplicated on namespace rename

### ISSUE THREAD

**Issue by freemanoid** [sidekiq-cron/sidekiq-cron#488]
### Summary

Version 2.0.0.rc1, 65020e5ff3ebd849516a925206aca523682dd64c

When you change a namespace for a job, it gets duplicated into a new namespace. So you end up having +1 job.

### How to reproduce

1. You have a single schedule

```ruby
sidekiq_cron do
  { :name => "Job1", :cron => "every 10 seconds" }
end
```

<img width="189" alt="Screenshot 2024-09-19 at 18 05 23" src="https://github.com/user-attachments/assets/39ee1b66-3798-4acb-ab0b-0af0b7490ee7">

2. Namespace "custom1" added to this schedule

```ruby
sidekiq_cron do
  { :name => "Job1", :cron => "every 10 seconds", :namespace => "custom1" }
end
```

<img width="313" alt="Screenshot 2024-09-19 at 18 06 29" src="https://github.com/user-attachments/assets/b52c4a59-5676-4c37-957b-98b8648e04cd">

3. Namespace changed to "custom2"

```ruby
sidekiq_cron do
  { :name => "Job1", :cron => "every 10 seconds", :namespace => "custom2" }
end
```

<img width="479" alt="Screenshot 2024-09-19 at 18 06 56" src="https://github.com/user-attachments/assets/c8e49555-8abe-430d-8c48-668451d369d7">

### Expected behavior

- After changing the namespace the schedule must be moved to a new namespace, not duplicated.

**Comment by zedtux** [comment]
To me this is not bug, simply because this gem has no notion of job update, or even job ID, as far as I know.

The way we are using it at my company is the following during a deployment:
1. Check if a job is gonna trigger in the next 5 minutes, if none continue, otherwise stop.
2. Clear all existing jobs from all namespaces
3. Re-create all scheduled jobs

We don't have any issue working that way.

Nonetheless we can try to find a way to manage this use case. What is this `sidekiq_cron` method doing?

**Comment by markets** [comment]
@zedtux Right! There is no "job update" concept, but if we can't find a workaround, at least we should document it or add a note in the [Namespaces section](https://github.com/sidekiq-cron/sidekiq-cron?tab=readme-ov-file#namespacing). Something like this could be enough: "If you change a job's namespace, you should manually clear old jobs in the previous namespace"

**Comment by freemanoid** [comment]
> * Clear all existing jobs from all namespaces

The only reason not to do it is that the user can change the job status (enabled/disabled) from the UI and it should persist between deployments.

**Comment by freemanoid** [comment]
> The only reason not to do it is that the user can change the job status (enabled/disabled) from the UI and it should persist between deployments.

The job status is currently stored in the job hash. Thus we want to "upsert" the new schedule over existing schedule in redis.

Given that job status is the only "state" that we need to persist between the deployments, we can rewrite the system to store job status separately from the rest of the job hash. Thus we can independently reload schedule and join status later if needed from a separate redis data structure. 

In this case on each deployment an entire schedule gets deleted, so job rename or namespace change is not a problem anymore. And the job status is loaded from a separate redis structure which persists between deployments.

**Comment by zedtux** [comment]
There’s nothing to fix, that’s not a bug, at least to me.

**Comment by zedtux** [comment]
Definitely updating the doc has to be done.

Please remove the “bug” label from this issue, and let’s rewrite it as a feature request with @freemanoid!

That would be great to follow a template like we can see in si many repo nowadays, with questions like “What is the expected behavior?”, “What is the current one?” And so on.

Then we could discuss the technical solution, but I would first have a look at Sidekiq way of managing jobs, I mean updating them, we will not re-create something already existing, right?

**Comment by jdaviderb** [comment]
@freemanoid @zedtux I had the same issue and I fixed removing the Cronjobs in the old namespace, something like this:

```ruby
Sidekiq::Cron::Job.all('YOUR_NAMENAME').each { |job| job.destroy }
```

**Comment by freemanoid** [comment]
> @freemanoid @zedtux I had the same issue and I fixed removing the Cronjobs in the old namespace, something like this:

There are a couple of downsides for this approach:
1. Enabled/disabled status won't be persisted after that.
2. It's easy to forget about running this script when you change the namespace
