### ISSUE TITLE
Cron v1.12.0 is incompatible with Sidekiq v7.3.4

### ISSUE THREAD

**Issue by leoarnold** [sidekiq-cron/sidekiq-cron#508]
The `#set` method changed its return value from instance of `Sidekiq::Job` to instance of `ActiveJob::ConfiguredJob`, hence we need `#perform_later` instead of `#perform_async`.

![Screenshot_2024-10-24_14-33-14](https://github.com/user-attachments/assets/426da04a-9051-4591-8698-9eedcbc8d06f)

Not sure if this should go into v2 or v1.12.1.

**Comment by markets** [comment]
I have no plans to release more versions based on the 1.X series. Could you please try the `v2.0.0.rc2`?

**Comment by paulhklam1122** [comment]
Further to this issue, `sidekiq-cron v1.12.0` is only compatible up to `sidekiq v7.3.2`

**Comment by leoarnold** [comment]
I pushed a fix in #510. I suggest to keep this issue open until a fixed version of `sidekiq-cron` is published, to avoid more issues being opened on the same problem.

**Comment by paulhklam1122** [comment]
#510 has been merged, please expedite releasing a new v2.0 as soon as possible please.

**Comment by leoarnold** [comment]
@paulhklam1122 Please don't rush an opensource maintainer. When people work for free, they deserve to do it on their own terms.

**Comment by paulhklam1122** [comment]
👍🏻

**Comment by paulhklam1122** [comment]
> @paulhklam1122 Please don't rush an opensource maintainer. When people work for free, they deserve to do it on their own terms.

👍🏻

**Comment by markets** [comment]
Hey @paulhklam1122 👋🏼 I know, I merged it by myself :) 

It will be released when it's ready, probably really soon (~ couple of weeks). The v2 branch contains a lot of changes (some of them structural), so cutting right now the final release is a very very bad idea. We are, in fact, in the process of launching some release candidates first in order to let people try all the changes and report any relevant issue. We already launched:
- RC1: https://github.com/sidekiq-cron/sidekiq-cron/releases/tag/v2.0.0.rc1
- RC2: https://github.com/sidekiq-cron/sidekiq-cron/releases/tag/v2.0.0.rc2
- Changes in master but still unreleased: https://github.com/sidekiq-cron/sidekiq-cron/compare/v2.0.0.rc2...master

In the meantime, you can already use the current state by pointing to GitHub master branch:

```
gem 'sidekiq-cron', github: 'sidekiq-cron'
```

If you want to help us, please do so ☝🏼 and report back that it works fine on your side. But adding messages like: "hey please release asap!" doesn't help to move forward. This project is quite complex (also our compatibility matrix) and I don't like to break apps. 

On the other hand, I'm currently actively maintaining a lot of OSS, so please 🙏🏼 if you want me to put more focus/efforts on your issues, at least consider sponsoring my OSS work: https://github.com/sponsors/markets

**Comment by leoarnold** [comment]
@markets I have a test system running Sidekiq 7.3.4 and Cron f0ac4038da7b3c6bc09b2c3ca9f0b9979848a95a. No problems so far. Keep those release candidates coming.

**Comment by markets** [comment]
Thanks a lot for your feedback @leoarnold 👌🏼 

Our next move is `v2.0.0.rc3` or probably the definitive `v2.0.0`. I'd like to wait like a couple of weeks more and then 🚀

**Comment by D-system** [comment]
I'm using the master branch on the last commit (https://github.com/sidekiq-cron/sidekiq-cron/commit/f0ac4038da7b3c6bc09b2c3ca9f0b9979848a95a) in production for a day with success.

Stats:
- 18 total cron jobs
- 1 disabled job
- 16 daily and hourly jobs
- 1 weekly job (running on Sunday)

The history with the JID are present and it is nice, thanks for that feature.

The human readable cron time works well if no timezone. With a timezone, it does not work (eg: `0 6 * * * Asia/Tokyo`).

**Comment by jmettraux** [comment]
@D-system wrote:
>
> The human readable cron time works well if no timezone. With a timezone, it does not work (eg: 0 6 * * * Asia/Tokyo).

Hello, do you mean `"every day at 6am Asia/Tokyo"` doesn't _schedule_?

**Comment by D-system** [comment]
@jmettraux It does schedule, I only taking about the human readable feature in the UI.

<img width="346" alt="image" src="https://github.com/user-attachments/assets/7275085c-24a2-4ddb-ac2a-2c8955710092">

**Comment by enstyled** [comment]
👋🏼 I am running RC2 since last week hoping to fix this issue, but my scheduled weekend job has failed today with the following stack trace:

<img width="857" alt="Screenshot 2024-11-03 at 09 47 26" src="https://github.com/user-attachments/assets/6f2d42b7-bad4-4b28-b57e-215e36227829">

This is on Rails 8 RC2, Ruby 3.3.5

**Comment by markets** [comment]
@enstyled you should use master branch for now or downgrade Sidekiq:

```
gem 'sidekiq-cron', github: 'sidekiq-cron'
```

**Comment by simonrentzke** [comment]
Master branch worked for me too, thanks @markets 👍

**Comment by markets** [comment]
Closing @leoarnold, v2 is out!

- https://rubygems.org/gems/sidekiq-cron/versions/2.0.0
- https://github.com/sidekiq-cron/sidekiq-cron/releases/tag/v2.0.0
